In [2]:
# 三層神經網絡
# 輸入層 Zeroth layer: 2 個神經元
# 第一隱藏層 1st layer: 3 個神經元
# 第二隱藏層 2nd layer: 2 個神經元
# 輸出層 3rd layer: 2 個神經元

import numpy as np

In [16]:
# 定義 sigmoid 函數
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
X = np.array([1.0, 0.5]) # 輸入訊號

In [5]:
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]) # 權重

In [6]:
B1 = np.array([0.1, 0.2, 0.3]) # 偏權值

In [9]:
print(X.shape)

(2,)


In [10]:
print(W1.shape)

(2, 3)


In [11]:
print(B1.shape)

(3,)


In [13]:
A1 = np.dot(X, W1) + B1

In [14]:
print(A1)

[ 0.3  0.7  1.1]


In [17]:
Z1 = sigmoid(A1)

In [18]:
print(Z1)

[ 0.57444252  0.66818777  0.75026011]


In [19]:
W2 = np.array([[0.1, 0.4],[0.2,0.5],[0.3,0.6]])

In [20]:
B2 = np.array([0.1, 0.2])

In [23]:
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [24]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [25]:
Z2

array([ 0.62624937,  0.7710107 ])

In [26]:
def identity_function(x):
    return x

In [27]:
W3 = np.array([[0.1, 0.3],[0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [28]:
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

In [29]:
Y

array([ 0.31682708,  0.69627909])

In [30]:
A3

array([ 0.31682708,  0.69627909])

In [31]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3],[0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

In [33]:
init_network()

{'W1': array([[ 0.1,  0.3,  0.5],
        [ 0.2,  0.4,  0.6]]), 'W2': array([[ 0.1,  0.4],
        [ 0.2,  0.5],
        [ 0.3,  0.6]]), 'W3': array([[ 0.1,  0.3],
        [ 0.2,  0.4]]), 'b1': array([ 0.1,  0.2,  0.3]), 'b2': array([ 0.1,  0.2]), 'b3': array([ 0.1,  0.2])}

In [34]:
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

In [36]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)

In [37]:
print(y)

[ 0.31682708  0.69627909]
