In [1]:
import numpy as np

In [11]:
a = np.array([0.3, 2.9, 4.0])
print(a)

[ 0.3  2.9  4. ]


In [12]:
exp_a = np.exp(a)  # 指數函數
print(exp_a)

[  1.34985881  18.17414537  54.59815003]


In [13]:
sum_exp_a = np.sum(exp_a)  # 上述指數函數求和
print(sum_exp_a)

74.1221542102


In [14]:
y = exp_a / sum_exp_a
print(y)

[ 0.01821127  0.24519181  0.73659691]


In [20]:
# 定義 softmax functiony 
# 注意 溢位Issue
def softmax(a):
    m1 = np.max(a)
    exp_a = np.exp(a - m1) # 解決溢位Issue
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [19]:
# 溢位Issue
b = np.array([1010, 100, 990])
np.exp(b) / np.sum(np.exp(b))

/Users/rei/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: overflow encountered in exp
  app.launch_new_instance()
/Users/rei/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


array([ nan,   0.,  nan])

In [21]:
c = np.array([1010, 100, 990])
softmax(c)

array([  9.99999998e-01,   0.00000000e+00,   2.06115362e-09])